# config of dataset preperation

artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  # source_URL: if u have data set url
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

# config for base model preperation

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5
